--- arch/arm/mach-tegra/Makefile
+++ arch/arm/mach-tegra/Makefile
@@ -13,6 +13,9 @@
 obj-y                                   += suspend.o
 obj-y                                   += fuse.o
 obj-y                                   += kfuse.o
+ifeq ($(CONFIG_ICS),y)
+obj-y                                   += csi.o
+endif
 obj-y                                   += i2c_error_recovery.o
 ifeq ($(CONFIG_TEGRA_ALSA),y)
 obj-$(CONFIG_ARCH_TEGRA_2x_SOC)         += tegra2_i2s.o
